version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8085
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - '8085:8085'
      - '6881:6881'
      - '6881:6881/udp'
    restart: unless-stopped